---

ubuntu_firewall_rules:
  - rule: allow
    port: 80
  - rule: allow
    port: 443

web_app_name: coffee
web_app_user: coffee
web_app_proxy_port: 5000
web_app_hostnames:
  - daileybrue.coffee
  - www.daileybrue.coffee
  - whosbuying.coffee
  - www.whosbuying.coffee

web_app_deployment_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZfHoDRNvjwnc5FJfwni/gvBDBHa6Pzj1Z9IOzN/94rqhCck625a7NLFURY9eikM61SUScqA/zhjAfF/GLpP8lh/r8x+7LP3fGD+cYgjEB8J5CO7A9EzrXlXVHuf34xsxwKwwkOHbH/SeejkqudhUhKzHjocmF6QjYuE5P30zn3HQHZlP+BuhCu58yGoFSUtmNaqsz5UZsFEddqswfJETe492EQ4+suaiWtA5FRZBzTdn1QUjKKeLbCFh1I6jOEMUO0CZh/ZNC/4XynSVNqhlszLGU6PR26UKbyXoSH10v4Xtv1t7Qa4L9CqDapv3N6UkjZkWvHQ3eDZveUsVEWV907P09b5FfTr5JfS4ck0PQn2v6GQZhOAVSapER3ozdJPmvvnSQcbCNY5qUGx3ReRIH76QkLHyFSsxJvgBfBizGxqhnPwLIBH/W0yc1d5l5pxXiBcjlcFgQ7/b44mgQqlxrihk8OToQCgN3mz0Js9q/H5lmbqXkmM9RkxDE7DiGsFc= steve@skarmory.local
