---

# name of the app executable and systemd socket / service
web_app_name: ~

# user that the app runs as and uses for its working directory
web_app_user: ~

# whether the web app is deployed as a JAR file
web_app_is_jar: no

# local port on which the web app listens (5000, 8000, 8080, etc)
web_app_proxy_port: ~

# extra systemd units that the app depends on
# (postgresql.service or redis.service, for example)
web_app_systemd_dependencies: []

# ssh authorized (public) key that GitHub Actions will use to deploy the app
# the corresponding private key must be setup as a GH secret: FOOBAR_SSH_KEY
web_app_deployment_key: ~

# list of dicts with keys: name, value
web_app_env_vars: []
